#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-OpenSoundControl
version:      0.05
version_from: lib/Net/OpenSoundControl.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
